### ISSUE TITLE
utils_dir undefined

### ISSUE THREAD

**Issue by cidrblock** [ansible-community/ansible.plugin_builder#15]
https://github.com/ansible-community/ansible.plugin_builder/blob/4a1eacd3c76dbc546af7284a3b4b6cf87a6c9300/roles/scaffold_plugins/tasks/template.yml#L88

I think the fix is:

```
     - name: Create utils file
        ansible.builtin.template:
          src: "plugin_utils/plugin.py.j2"
          dest: "{{ parent_directory }}/plugin_utils/{{ plugin['name'] }}.py"
        when: not file_stat.stat.exists
```
